version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: template-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: duc
      POSTGRES_PASSWORD: "080103"
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init-databases.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U duc"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
